# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('primary_attr', models.CharField(choices=[('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence')], max_length=3)),
                ('str_base', models.PositiveSmallIntegerField()),
                ('str_gain', models.FloatField()),
                ('agi_base', models.PositiveSmallIntegerField()),
                ('agi_gain', models.FloatField()),
                ('int_base', models.PositiveSmallIntegerField()),
                ('int_gain', models.FloatField()),
                ('regen_base', models.FloatField()),
                ('armor_base', models.FloatField()),
                ('move_base', models.PositiveSmallIntegerField()),
                ('turn_speed', models.FloatField()),
                ('dmg_min_base', models.PositiveSmallIntegerField()),
                ('dmg_max_base', models.PositiveSmallIntegerField()),
                ('atk_range', models.PositiveSmallIntegerField()),
                ('base_atk_time', models.FloatField()),
                ('vision_range_day', models.PositiveSmallIntegerField()),
                ('vision_range_night', models.PositiveSmallIntegerField()),
                ('model_size', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
